
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FASTService
{

using System;
    using System.Collections.Generic;
    
public partial class AccessLevel
{

    public short AccessLevelID { get; set; }

    public string AccessMode { get; set; }

    public string Description { get; set; }

}

}
