//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public long AuditTrailID { get; set; }
        public System.DateTime Date { get; set; }
        public int EmployeeID { get; set; }
        public string Action { get; set; }
        public string AdditionalInformation { get; set; }
        public string AssetTag { get; set; }
        public string AssignmentID { get; set; }
    }
}
