//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FASTDBModel : DbContext
    {
        public FASTDBModel()
            : base("name=FASTDBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessRight> AccessRights { get; set; }
        public virtual DbSet<AssetAssignment> AssetAssignments { get; set; }
        public virtual DbSet<AssetClass> AssetClasses { get; set; }
        public virtual DbSet<AssetStatu> AssetStatus { get; set; }
        public virtual DbSet<AssetType> AssetTypes { get; set; }
        public virtual DbSet<AssignmentStatu> AssignmentStatus { get; set; }
        public virtual DbSet<AuditTrail> AuditTrails { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Download> Downloads { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FixAsset> FixAssets { get; set; }
        public virtual DbSet<Issuer> Issuers { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<vwAccessRight> vwAccessRights { get; set; }
        public virtual DbSet<vwAssetAssignment> vwAssetAssignments { get; set; }
        public virtual DbSet<vwAssetAssignmentsForCustodian> vwAssetAssignmentsForCustodians { get; set; }
        public virtual DbSet<vwAssetAssignmentsForManager> vwAssetAssignmentsForManagers { get; set; }
        public virtual DbSet<vwAssetAssignmentsForMI> vwAssetAssignmentsForMIS { get; set; }
        public virtual DbSet<vwCustodiansList> vwCustodiansLists { get; set; }
        public virtual DbSet<vwDepartmentList> vwDepartmentLists { get; set; }
        public virtual DbSet<vwEmployeeList> vwEmployeeLists { get; set; }
        public virtual DbSet<vwEmployee> vwEmployees { get; set; }
        public virtual DbSet<vwFixAssetList> vwFixAssetLists { get; set; }
        public virtual DbSet<vwFixAsset> vwFixAssets { get; set; }
        public virtual DbSet<vwManagersList> vwManagersLists { get; set; }
        public virtual DbSet<vwMISList> vwMISLists { get; set; }
        public virtual DbSet<BulkUpload> BulkUploads { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<AccessLevel> AccessLevels { get; set; }
        public virtual DbSet<ReasonCode> ReasonCodes { get; set; }
    }
}
