//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int RegistrationID { get; set; }
        public int EmployeeID { get; set; }
        public string Password { get; set; }
        public short Status { get; set; }
        public System.DateTime DateStamp { get; set; }
    }
}
