//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkUpload
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> TotalRecords { get; set; }
        public Nullable<int> TotalInserts { get; set; }
        public int Status { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
