//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int ConfigID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<bool> IsEncrypted { get; set; }
        public Nullable<bool> CanExpire { get; set; }
        public Nullable<int> ExpiryDays { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
